package com.auca.student_registration_system.entity;

import com.auca.student_registration_system.constants.EAcademicUnitType;
import lombok.*;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import jakarta.persistence.*;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;
import java.time.LocalDateTime;
import java.util.HashSet;
import java.util.Set;

/**
 * Represents a hierarchical academic unit in the university structure.
 * Supports three levels: FACULTY (top), PROGRAMME (middle), DEPARTMENT (bottom).
 * Academic units are organized in a tree structure with parent-child relationships.
 *
 * @author Architecture Team
 * @version 1.0
 */
@Entity
@Table(
    name = "academic_units",
    indexes = {
        @Index(name = "idx_au_code", columnList = "code", unique = true),
        @Index(name = "idx_au_parent_id", columnList = "parent_id"),
        @Index(name = "idx_au_type", columnList = "type")
    }
)
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
@EqualsAndHashCode(exclude = {"parent", "children", "createdAt", "updatedAt"})
@ToString(exclude = {"parent", "children", "createdAt", "updatedAt"})
public class AcademicUnit {

    /**
     * Unique identifier for the academic unit.
     * Auto-generated by database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id")
    private Long id;

    /**
     * Unique code for the academic unit.
     * Used for identification and reference in reports.
     * Range: 3-20 characters
     */
    @Column(name = "code", unique = true, nullable = false, length = 20)
    @NotBlank(message = "Academic unit code cannot be blank")
    @Size(
        min = 3,
        max = 20,
        message = "Academic unit code must be between 3 and 20 characters"
    )
    private String code;

    /**
     * Display name of the academic unit.
     * Examples: "Faculty of Engineering", "Computer Science Programme", "SE Department"
     */
    @Column(name = "name", nullable = false, length = 255)
    @NotBlank(message = "Academic unit name cannot be blank")
    @Size(
        max = 255,
        message = "Academic unit name must not exceed 255 characters"
    )
    private String name;

    /**
     * Type of academic unit.
     * Values: FACULTY (top-level), PROGRAMME (middle), DEPARTMENT (lowest)
     * Maps to enum stored as STRING in database.
     */
    @Column(name = "type", nullable = false)
    @Enumerated(EnumType.STRING)
    @NotNull(message = "Academic unit type cannot be null")
    private EAcademicUnitType type;

    /**
     * Parent academic unit (self-referential).
     * For FACULTY units, this is null (top-level).
     * For PROGRAMME and DEPARTMENT, this references the parent unit.
     * 
     * Example hierarchy:
     * - Faculty (parent = null)
     *   - Programme (parent = Faculty)
     *     - Department (parent = Programme)
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "parent_id")
    private AcademicUnit parent;

    /**
     * Child academic units (self-referential).
     * One-to-many relationship with AcademicUnit via parent reference.
     * Populated when loading parent with children.
     */
    @OneToMany(
        mappedBy = "parent",
        cascade = CascadeType.ALL,
        orphanRemoval = true,
        fetch = FetchType.LAZY
    )
    @Builder.Default
    private Set<AcademicUnit> children = new HashSet<>();

    /**
     * Timestamp when this academic unit record was created.
     * Set automatically on entity creation.
     */
    @Column(name = "created_at", nullable = false, updatable = false)
    @CreationTimestamp
    private LocalDateTime createdAt;

    /**
     * Timestamp when this academic unit record was last updated.
     * Updated automatically on entity modification.
     */
    @Column(name = "updated_at")
    @UpdateTimestamp
    private LocalDateTime updatedAt;
}
