package com.auca.student_registration_system.entity;

import com.auca.student_registration_system.constants.ECourseStatus;
import lombok.*;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import jakarta.persistence.*;
import jakarta.validation.constraints.Max;
import jakarta.validation.constraints.Min;
import jakarta.validation.constraints.NotNull;
import java.time.LocalDateTime;

/**
 * Represents a specific offering of a course in a particular semester.
 * A course is an offering that combines a course definition with a semester and academic unit.
 * Each course has an assigned tutor and optional assistant tutor.
 *
 * @author Architecture Team
 * @version 1.0
 */
@Entity
@Table(
    name = "courses",
    indexes = {
        @Index(name = "idx_course_definition_id", columnList = "course_definition_id"),
        @Index(name = "idx_course_semester_id", columnList = "semester_id"),
        @Index(name = "idx_course_academic_unit_id", columnList = "academic_unit_id"),
        @Index(name = "idx_course_tutor_id", columnList = "tutor_id"),
        @Index(name = "idx_course_assistant_tutor_id", columnList = "assistant_tutor_id"),
        @Index(name = "idx_course_status", columnList = "status"),
        @Index(
            name = "idx_course_unique_offering",
            columnList = "course_definition_id, semester_id, academic_unit_id",
            unique = true
        )
    }
)
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
@EqualsAndHashCode(exclude = {"courseDefinition", "semester", "academicUnit", "tutor", "assistantTutor", "createdAt", "updatedAt"})
@ToString(exclude = {"courseDefinition", "semester", "academicUnit", "tutor", "assistantTutor", "createdAt", "updatedAt"})
public class Course {

    /**
     * Unique identifier for the course offering.
     * Auto-generated by database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id")
    private Long id;

    /**
     * Reference to the course definition/template.
     * Defines permanent course information (code, credits, etc.).
     * Many course offerings can reference the same definition across semesters.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "course_definition_id", nullable = false)
    @NotNull(message = "Course definition cannot be null")
    private CourseDefinition courseDefinition;

    /**
     * Reference to the semester in which this course is offered.
     * Determines when the course runs and when students can register.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "semester_id", nullable = false)
    @NotNull(message = "Semester cannot be null")
    private Semester semester;

    /**
     * Reference to the academic unit (department) offering this course.
     * Indicates which department is responsible for this offering.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "academic_unit_id", nullable = false)
    @NotNull(message = "Academic unit cannot be null")
    private AcademicUnit academicUnit;

    /**
     * Primary tutor/instructor for this course.
     * Required for all courses.
     * Must be a valid teacher with appropriate qualification.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "tutor_id", nullable = false)
    @NotNull(message = "Tutor cannot be null")
    private Teacher tutor;

    /**
     * Assistant tutor/instructor for this course.
     * Optional - not all courses have an assistant tutor.
     * Supports team-teaching when needed.
     * Cannot be the same as primary tutor (validated in service layer).
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "assistant_tutor_id")
    private Teacher assistantTutor;

    /**
     * Maximum enrollment capacity for this course offering.
     * Limits the number of students who can register.
     * Range: 1-500 students per academic guidelines.
     * System will prevent additional registrations once capacity is reached.
     */
    @Column(name = "maximum_capacity", nullable = false)
    @NotNull(message = "Maximum capacity cannot be null")
    @Min(
        value = 1,
        message = "Course must have capacity for at least 1 student"
    )
    @Max(
        value = 500,
        message = "Course capacity cannot exceed 500 students"
    )
    private Integer maximumCapacity;

    /**
     * Status of the course offering.
     * Values: OFFERED, CLOSED, CANCELLED
     * - OFFERED: Course is available for student registration
     * - CLOSED: Course is full or registration closed, no new registrations allowed
     * - CANCELLED: Course offering has been cancelled
     */
    @Column(name = "status", nullable = false)
    @Enumerated(EnumType.STRING)
    @NotNull(message = "Course status cannot be null")
    @Builder.Default
    private ECourseStatus status = ECourseStatus.OFFERED;

    /**
     * Timestamp when this course offering was created.
     * Set automatically on entity creation.
     */
    @Column(name = "created_at", nullable = false, updatable = false)
    @CreationTimestamp
    private LocalDateTime createdAt;

    /**
     * Timestamp when this course offering was last updated.
     * Updated automatically on entity modification.
     */
    @Column(name = "updated_at")
    @UpdateTimestamp
    private LocalDateTime updatedAt;
}
