package com.auca.student_registration_system.entity;

import com.auca.student_registration_system.constants.AppConstants;
import lombok.*;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import jakarta.persistence.*;
import jakarta.validation.constraints.*;
import java.time.LocalDateTime;

/**
 * Represents a course definition/template in the university catalog.
 * Course definitions are reusable templates that can be offered in multiple semesters.
 * Stores permanent course information that does not change across offerings.
 *
 * @author Architecture Team
 * @version 1.0
 */
@Entity
@Table(
    name = "course_definitions",
    indexes = {
        @Index(name = "idx_cd_code", columnList = "code", unique = true),
        @Index(name = "idx_cd_name", columnList = "name")
    }
)
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
@EqualsAndHashCode(exclude = {"createdAt", "updatedAt"})
@ToString(exclude = {"createdAt", "updatedAt"})
public class CourseDefinition {

    /**
     * Unique identifier for the course definition.
     * Auto-generated by database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id")
    private Long id;

    /**
     * Unique course code.
     * Used for course identification and prerequisites specification.
     * Examples: CS101, MATH201, ENG301
     * Range: 3-20 characters
     */
    @Column(name = "code", unique = true, nullable = false, length = 20)
    @NotBlank(message = "Course code cannot be blank")
    @Size(
        min = 3,
        max = 20,
        message = "Course code must be between 3 and 20 characters"
    )
    private String code;

    /**
     * Course name/title.
     * Display name for the course in UI and reports.
     */
    @Column(name = "name", nullable = false, length = 255)
    @NotBlank(message = "Course name cannot be blank")
    @Size(
        max = 255,
        message = "Course name must not exceed 255 characters"
    )
    private String name;

    /**
     * Detailed course description.
     * Contains learning outcomes, syllabus summary, etc.
     * Optional but recommended for all courses.
     */
    @Column(name = "description", columnDefinition = "TEXT")
    @Size(
        max = 1000,
        message = "Course description must not exceed 1000 characters"
    )
    private String description;

    /**
     * Number of credit hours for this course.
     * Range: 1-12 credits per academic guidelines.
     * Typically: 3 credits for regular courses, 6 for intensive, etc.
     * 
     * Validation: must be between AppConstants.MIN_CREDITS and AppConstants.MAX_CREDITS
     */
    @Column(name = "credits", nullable = false)
    @NotNull(message = "Course credits cannot be null")
    @Min(
        value = 1,
        message = "Course must have at least 1 credit"
    )
    @Max(
        value = 12,
        message = "Course cannot exceed 12 credits"
    )
    private Integer credits;

    /**
     * Comma-separated list of prerequisite course codes.
     * Example: "CS101,CS102,MATH101"
     * Used for validation when students register for courses.
     * Optional if no prerequisites required.
     */
    @Column(name = "prerequisites", columnDefinition = "TEXT")
    private String prerequisites;

    /**
     * Timestamp when this course definition was created.
     * Set automatically on entity creation.
     */
    @Column(name = "created_at", nullable = false, updatable = false)
    @CreationTimestamp
    private LocalDateTime createdAt;

    /**
     * Timestamp when this course definition was last updated.
     * Updated automatically on entity modification.
     */
    @Column(name = "updated_at")
    @UpdateTimestamp
    private LocalDateTime updatedAt;
}
