package com.auca.student_registration_system.entity;

import com.auca.student_registration_system.constants.ESemesterStatus;
import lombok.*;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import jakarta.persistence.*;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;
import java.time.LocalDate;
import java.time.LocalDateTime;

/**
 * Represents an academic semester/term in the university system.
 * Controls academic calendar, course offerings, and student registration periods.
 * Only one semester can be ACTIVE at any given time.
 *
 * @author Architecture Team
 * @version 1.0
 */
@Entity
@Table(
    name = "semesters",
    indexes = {
        @Index(name = "idx_semester_id", columnList = "semester_id", unique = true),
        @Index(name = "idx_semester_status", columnList = "status"),
        @Index(name = "idx_semester_dates", columnList = "start_date, end_date")
    }
)
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
@EqualsAndHashCode(exclude = {"createdAt", "updatedAt"})
@ToString(exclude = {"createdAt", "updatedAt"})
public class Semester {

    /**
     * Unique identifier for the semester entity.
     * Auto-generated by database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id")
    private Long id;

    /**
     * Unique semester identifier.
     * Format examples: "2024-SPRING", "2024-FALL", "2024-SUMMER"
     * Used as business key for semester identification.
     */
    @Column(name = "semester_id", unique = true, nullable = false, length = 50)
    @NotBlank(message = "Semester ID cannot be blank")
    @Size(
        max = 50,
        message = "Semester ID must not exceed 50 characters"
    )
    private String semesterId;

    /**
     * Display name of the semester.
     * Examples: "Spring 2024", "Fall 2024", "Summer 2024"
     * Used in UI and reports.
     */
    @Column(name = "name", nullable = false, length = 100)
    @NotBlank(message = "Semester name cannot be blank")
    @Size(
        max = 100,
        message = "Semester name must not exceed 100 characters"
    )
    private String name;

    /**
     * Start date of the semester.
     * First day of academic period for this semester.
     * Must be before end date.
     */
    @Column(name = "start_date", nullable = false)
    @NotNull(message = "Semester start date cannot be null")
    private LocalDate startDate;

    /**
     * End date of the semester.
     * Last day of academic period for this semester.
     * Must be after start date.
     */
    @Column(name = "end_date", nullable = false)
    @NotNull(message = "Semester end date cannot be null")
    private LocalDate endDate;

    /**
     * Status of the semester.
     * Values: PLANNED, ACTIVE, COMPLETED, CLOSED
     * - PLANNED: Semester is scheduled but not started
     * - ACTIVE: Semester is ongoing, registration is open
     * - COMPLETED: Semester has ended, final marks recorded
     * - CLOSED: Semester closed, no further changes allowed
     * 
     * Business Rule: Only ONE semester can have status = ACTIVE at any time.
     */
    @Column(name = "status", nullable = false)
    @Enumerated(EnumType.STRING)
    @NotNull(message = "Semester status cannot be null")
    @Builder.Default
    private ESemesterStatus status = ESemesterStatus.PLANNED;

    /**
     * Timestamp when this semester record was created.
     * Set automatically on entity creation.
     */
    @Column(name = "created_at", nullable = false, updatable = false)
    @CreationTimestamp
    private LocalDateTime createdAt;

    /**
     * Timestamp when this semester record was last updated.
     * Updated automatically on entity modification.
     */
    @Column(name = "updated_at")
    @UpdateTimestamp
    private LocalDateTime updatedAt;
}
