package com.auca.student_registration_system.entity;

import lombok.*;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import jakarta.persistence.*;
import jakarta.validation.constraints.*;
import java.time.LocalDate;
import java.time.LocalDateTime;

/**
 * Represents a student enrolled in the university system.
 * Stores student demographic information and tracks student status.
 * Each student has a unique registration number.
 *
 * @author Architecture Team
 * @version 1.0
 */
@Entity
@Table(
    name = "students",
    indexes = {
        @Index(name = "idx_student_reg_no", columnList = "reg_no", unique = true),
        @Index(name = "idx_student_email", columnList = "email", unique = true),
        @Index(name = "idx_student_name", columnList = "first_name, last_name")
    }
)
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
@EqualsAndHashCode(exclude = {"createdAt", "updatedAt"})
@ToString(exclude = {"createdAt", "updatedAt"})
public class Student {

    /**
     * Unique identifier for the student entity.
     * Auto-generated by database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id")
    private Long id;

    /**
     * Unique student registration number.
     * Assigned at enrollment and never changes.
     * Used as business identifier in all student-related communications.
     * Format varies by institution (e.g., "STU-2024-0001", "20240001").
     * Range: 3-20 characters
     */
    @Column(name = "reg_no", unique = true, nullable = false, length = 20)
    @NotBlank(message = "Student registration number cannot be blank")
    @Size(
        min = 3,
        max = 20,
        message = "Student registration number must be between 3 and 20 characters"
    )
    private String regNo;

    /**
     * Student's first name(s).
     */
    @Column(name = "first_name", nullable = false, length = 100)
    @NotBlank(message = "First name cannot be blank")
    @Size(
        max = 100,
        message = "First name must not exceed 100 characters"
    )
    private String firstName;

    /**
     * Student's last name(s) / family name.
     */
    @Column(name = "last_name", nullable = false, length = 100)
    @NotBlank(message = "Last name cannot be blank")
    @Size(
        max = 100,
        message = "Last name must not exceed 100 characters"
    )
    private String lastName;

    /**
     * Student's date of birth.
     * Must be a valid date in the past (no future dates).
     * Used for age verification and demographic reporting.
     */
    @Column(name = "date_of_birth", nullable = false)
    @NotNull(message = "Date of birth cannot be null")
    @PastOrPresent(message = "Date of birth must be in the past or present")
    private LocalDate dateOfBirth;

    /**
     * Student's email address.
     * Must be unique across all students.
     * Used for notifications, password resets, and communications.
     * Follows standard email format validation.
     */
    @Column(name = "email", unique = true, nullable = false, length = 255)
    @NotBlank(message = "Email cannot be blank")
    @Email(message = "Email must be valid")
    @Size(
        max = 255,
        message = "Email must not exceed 255 characters"
    )
    private String email;

    /**
     * Student's phone number.
     * Optional contact information for student communications.
     * Format is flexible - system does not enforce specific format.
     */
    @Column(name = "phone", length = 20)
    @Size(
        max = 20,
        message = "Phone number must not exceed 20 characters"
    )
    private String phone;

    /**
     * Student's gender.
     * Optional demographic information.
     * Accepted values: "M", "F", "Other", or null
     */
    @Column(name = "gender", length = 50)
    @Size(
        max = 50,
        message = "Gender must not exceed 50 characters"
    )
    private String gender;

    /**
     * Current status of the student in the system.
     * Examples: "ACTIVE", "INACTIVE", "GRADUATED", "WITHDRAWN"
     * Defaults to "ACTIVE" when student is first registered.
     */
    @Column(name = "status", length = 50)
    @Builder.Default
    private String status = "ACTIVE";

    /**
     * Timestamp when this student record was created.
     * Set automatically on entity creation.
     */
    @Column(name = "created_at", nullable = false, updatable = false)
    @CreationTimestamp
    private LocalDateTime createdAt;

    /**
     * Timestamp when this student record was last updated.
     * Updated automatically on entity modification.
     */
    @Column(name = "updated_at")
    @UpdateTimestamp
    private LocalDateTime updatedAt;
}
