package com.auca.student_registration_system.entity;

import com.auca.student_registration_system.constants.ERegistrationStatus;
import lombok.*;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import jakarta.persistence.*;
import jakarta.validation.constraints.NotNull;
import java.time.LocalDate;
import java.time.LocalDateTime;

/**
 * Represents a student's registration/enrollment in a specific semester.
 * Links a student to a semester and tracks their registration status.
 * Each student can only register once per semester (enforced by unique constraint).
 *
 * @author Architecture Team
 * @version 1.0
 */
@Entity
@Table(
    name = "student_registrations",
    indexes = {
        @Index(name = "idx_sr_student_id", columnList = "student_id"),
        @Index(name = "idx_sr_semester_id", columnList = "semester_id"),
        @Index(name = "idx_sr_status", columnList = "status"),
        @Index(
            name = "idx_sr_unique_registration",
            columnList = "student_id, semester_id",
            unique = true
        )
    }
)
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
@EqualsAndHashCode(exclude = {"student", "semester", "createdAt", "updatedAt"})
@ToString(exclude = {"student", "semester", "createdAt", "updatedAt"})
public class StudentRegistration {

    /**
     * Unique identifier for the student registration record.
     * Auto-generated by database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id")
    private Long id;

    /**
     * Reference to the student who is registering.
     * The student entity contains permanent student information.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "student_id", nullable = false)
    @NotNull(message = "Student cannot be null")
    private Student student;

    /**
     * Reference to the semester for which the student is registering.
     * Establishes which academic period this registration applies to.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "semester_id", nullable = false)
    @NotNull(message = "Semester cannot be null")
    private Semester semester;

    /**
     * Date on which the student registered for this semester.
     * Typically the date the registration was created.
     * Used for tracking registration timeline and audit purposes.
     */
    @Column(name = "registration_date", nullable = false)
    @NotNull(message = "Registration date cannot be null")
    private LocalDate registrationDate;

    /**
     * Current status of the student's registration for this semester.
     * Values: REGISTERED, WITHDRAWN, COMPLETED
     * - REGISTERED: Student is actively registered and can take courses
     * - WITHDRAWN: Student has withdrawn from the semester
     * - COMPLETED: Semester is complete, grades have been finalized
     */
    @Column(name = "status", nullable = false)
    @Enumerated(EnumType.STRING)
    @NotNull(message = "Registration status cannot be null")
    @Builder.Default
    private ERegistrationStatus status = ERegistrationStatus.REGISTERED;

    /**
     * Timestamp when this registration record was created.
     * Set automatically on entity creation.
     */
    @Column(name = "created_at", nullable = false, updatable = false)
    @CreationTimestamp
    private LocalDateTime createdAt;

    /**
     * Timestamp when this registration record was last updated.
     * Updated automatically on entity modification.
     */
    @Column(name = "updated_at")
    @UpdateTimestamp
    private LocalDateTime updatedAt;
}
