package com.auca.student_registration_system.entity;

import lombok.*;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import javax.persistence.*;
import javax.validation.constraints.*;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;

/**
 * Represents a student's enrollment in a specific course.
 * Tracks course enrollment, grades, marks, and GPA contribution.
 * Each student can only enroll in each course once per semester (enforced by unique constraint).
 *
 * @author Architecture Team
 * @version 1.0
 */
@Entity
@Table(
    name = "student_courses",
    indexes = {
        @Index(name = "idx_sc_student_registration_id", columnList = "student_registration_id"),
        @Index(name = "idx_sc_course_id", columnList = "course_id"),
        @Index(
            name = "idx_sc_unique_enrollment",
            columnList = "student_registration_id, course_id",
            unique = true
        )
    }
)
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
@EqualsAndHashCode(exclude = {"studentRegistration", "course", "createdAt", "updatedAt"})
@ToString(exclude = {"studentRegistration", "course", "createdAt", "updatedAt"})
public class StudentCourse {

    /**
     * Unique identifier for the student course enrollment record.
     * Auto-generated by database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id")
    private Long id;

    /**
     * Reference to the student's semester registration.
     * Links this course enrollment to the parent registration.
     * Provides context of which semester this course is being taken.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "student_registration_id", nullable = false)
    @NotNull(message = "Student registration cannot be null")
    private StudentRegistration studentRegistration;

    /**
     * Reference to the course offering the student enrolled in.
     * Contains information about the course definition, tutor, and semester.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "course_id", nullable = false)
    @NotNull(message = "Course cannot be null")
    private Course course;

    /**
     * Number of credits awarded for this course.
     * Typically equals the course definition's credit hours.
     * Range: 1-12 credits per academic guidelines.
     */
    @Column(name = "credits", nullable = false)
    @NotNull(message = "Credits cannot be null")
    @Min(
        value = 1,
        message = "Course must have at least 1 credit"
    )
    @Max(
        value = 12,
        message = "Course cannot exceed 12 credits"
    )
    private Integer credits;

    /**
     * Marks/score obtained by the student in this course.
     * Typically on a 0-100 scale, but system supports any numeric value.
     * Nullable - populated after grading is completed.
     * Precision: 5 digits total, 2 decimal places.
     */
    @Column(name = "marks", precision = 5, scale = 2)
    @DecimalMin(
        value = "0",
        message = "Marks cannot be negative"
    )
    @DecimalMax(
        value = "100",
        message = "Marks cannot exceed 100"
    )
    private BigDecimal marks;

    /**
     * Letter grade assigned to the student for this course.
     * Examples: "A", "B+", "C", "D", "F"
     * Nullable - populated after marks are recorded and grading schema applied.
     * Exact format depends on institutional grading scale.
     */
    @Column(name = "grade", length = 2)
    @Size(
        max = 2,
        message = "Grade must not exceed 2 characters"
    )
    private String grade;

    /**
     * Grade Point Average (GPA) contribution for this course.
     * Calculated from grade using institutional GPA scale.
     * Typically on a 4.0 scale: A=4.0, B=3.0, C=2.0, D=1.0, F=0.0
     * Nullable - populated after grade is assigned.
     * Precision: 3 digits total, 2 decimal places (range 0.00-4.00).
     */
    @Column(name = "gpa", precision = 3, scale = 2)
    @DecimalMin(
        value = "0.0",
        message = "GPA cannot be negative"
    )
    @DecimalMax(
        value = "4.0",
        message = "GPA cannot exceed 4.0"
    )
    private BigDecimal gpa;

    /**
     * Additional remarks or comments about the student's performance.
     * Optional field for instructor comments, notes, or special circumstances.
     */
    @Column(name = "remarks", columnDefinition = "TEXT")
    private String remarks;

    /**
     * Date on which the student enrolled in this course.
     * Typically the course start date or student registration date.
     * Used for enrollment timeline and audit purposes.
     */
    @Column(name = "enrollment_date", nullable = false)
    @NotNull(message = "Enrollment date cannot be null")
    private LocalDate enrollmentDate;

    /**
     * Timestamp when this student course record was created.
     * Set automatically on entity creation.
     */
    @Column(name = "created_at", nullable = false, updatable = false)
    @CreationTimestamp
    private LocalDateTime createdAt;

    /**
     * Timestamp when this student course record was last updated.
     * Updated automatically on entity modification.
     */
    @Column(name = "updated_at")
    @UpdateTimestamp
    private LocalDateTime updatedAt;
}
