package com.auca.student_registration_system.entity;

import com.auca.student_registration_system.constants.EQualification;
import lombok.*;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import jakarta.persistence.*;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Size;
import java.time.LocalDateTime;

/**
 * Represents a teacher/lecturer in the university system.
 * Stores teacher information including qualifications and tracks course assignments.
 *
 * @author Architecture Team
 * @version 1.0
 */
@Entity
@Table(
    name = "teachers",
    indexes = {
        @Index(name = "idx_teacher_code", columnList = "code", unique = true),
        @Index(name = "idx_teacher_names", columnList = "names")
    }
)
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
@EqualsAndHashCode(exclude = {"createdAt", "updatedAt"})
@ToString(exclude = {"createdAt", "updatedAt"})
public class Teacher {

    /**
     * Unique identifier for the teacher.
     * Auto-generated by database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id")
    private Long id;

    /**
     * Unique teacher code/identifier.
     * Must be unique across the system.
     * Range: 3-20 characters
     */
    @Column(name = "code", unique = true, nullable = false, length = 20)
    @NotBlank(message = "Teacher code cannot be blank")
    @Size(
        min = 3,
        max = 20,
        message = "Teacher code must be between 3 and 20 characters"
    )
    private String code;

    /**
     * Full name(s) of the teacher.
     */
    @Column(name = "names", nullable = false, length = 255)
    @NotBlank(message = "Teacher name cannot be blank")
    @Size(
        max = 255,
        message = "Teacher name must not exceed 255 characters"
    )
    private String names;

    /**
     * Professional qualification of the teacher.
     * Enum values: MASTER, PHD, PROFESSOR
     * Maps to database string value via JPA converter.
     */
    @Column(name = "qualification", nullable = false)
    @Enumerated(EnumType.STRING)
    @Builder.Default
    private EQualification qualification = EQualification.MASTER;

    /**
     * Timestamp when this teacher record was created.
     * Set automatically on entity creation.
     */
    @Column(name = "created_at", nullable = false, updatable = false)
    @CreationTimestamp
    private LocalDateTime createdAt;

    /**
     * Timestamp when this teacher record was last updated.
     * Updated automatically on entity modification.
     */
    @Column(name = "updated_at")
    @UpdateTimestamp
    private LocalDateTime updatedAt;
}
